services:
    back-end:
      build:
        context: ./back-end
        dockerfile: Dockerfile
      image: "softy-pinko-back-end:latest"
      ports:
      - "5252:5252"

    front-end:
      build:
        context: ./front-end
        dockerfile: Dockerfile
      image: "softy-pinko-front-end:latest"
      ports:
        - "9000:9000"
      depends_on:
        - back-end

    proxy:
      build:
        context: ./proxy
        dockerfile: Dockerfile
      image: "softy-pinko-proxy:task-5"
      ports:
        - "80:80"
      depends_on:
        - back-end
        - front-end